package DataDictionaryDSLLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Agregation = 0;
  public static final int DomainInfo = 1;
  public static final int DomainInstance = 2;
  public static final int DomainTable = 3;
  public static final int ExclusiveSpecialization = 4;
  public static final int Field = 5;
  public static final int NonExclusiveSpecialization = 6;
  public static final int Reference = 7;
  public static final int Set = 8;
  public static final int Structure = 9;
  public static final int StructureReference = 10;
  public static final int StructureRepository = 11;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xc81a5de5c82046dcL, 0xb13e1fa2a0dad109L);
    builder.put(0x6f4b224578073b01L, Agregation);
    builder.put(0x1052e67ff6c57e8bL, DomainInfo);
    builder.put(0x1052e67ff6c3eed4L, DomainInstance);
    builder.put(0x1052e67ff6c3eec2L, DomainTable);
    builder.put(0x6f4b224578078449L, ExclusiveSpecialization);
    builder.put(0x6f4b22457807455dL, Field);
    builder.put(0xd2d707c97ae7ba8L, NonExclusiveSpecialization);
    builder.put(0x1052e67ff6c6005eL, Reference);
    builder.put(0x1052e67ff6c07d59L, Set);
    builder.put(0x6f4b224578073afdL, Structure);
    builder.put(0x6f4b22457808af51L, StructureReference);
    builder.put(0x6f4b224578073e21L, StructureRepository);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
